# Playbook is list of plays
- name: PLAY-1
  hosts: localhost
  tasks: 
  - name: PLAY-1 and TASK-1
    ansible.buildin.debug
      msg: "Hi, this is PLAY1 & TASK1"


- name: PLAY-2
  hosts: localhost
  tasks: 
  - name: PLAY-2 and TASK-2
    ansible.buildin.debug
      msg: "Hi, this is PLAY2 & TASK2"