#TASK level variables
- name: variables from play level
  hosts: localhost
  vars: 
    course: "DevOps"
    trainer: "Shivakumar"
    duration: "110hrs"
  tasks:
  - name: check variables 
    vars: #task level
     course: "i was learning AWS" 
    ansible.builtin.debug:
       msg: "Hi, iam learning {{course}}, by {{trainer}}, duration is {{duration}}"

# task level variables can override play level variables