- name: variables from play level
  hosts: localhost
  tasks:
  - name: check variables 
    ansible.builtin.debug:
       msg: "Hi, iam learning {{course}}, by {{trainer}}, duration is {{duration}}"

